CONTRACT_ADDRESS:
  Polygon:
    chain_id: 137 # This is the mainnet chain ID for Polygon. Replace if using a testnet or different network.
    rpc_endpoint: "https://polygon-bor-rpc.publicnode.com" # Replace with your RPC endpoint URL
    address: "0x3B820FcDF4a86B145da82041Da06b10039b8F27B" # Your contract's address
    abi: "[{\"constant\": true, \"inputs\": [], \"name\": \"name\", \"outputs\": [{\"name\": \"\", \"type\": \"string\"}], \"payable\": false, \"stateMutability\": \"view\", \"type\": \"function\"}]" # Simplified ABI; replace with your contract's actual ABI

  Klaytn:
    chain_id: 8217 # Mainnet chain ID for Klaytn
    rpc_endpoint: "https://public-en-cypress.klaytn.net" # Replace with your RPC endpoint URL
    address: "0x3c83ddf11644bfd7eb969a065424483dbe95dcf4" # Your contract's address
    abi: "[{\"constant\": true, \"inputs\": [], \"name\": \"name\", \"outputs\": [{\"name\": \"\", \"type\": \"string\"}], \"payable\": false, \"stateMutability\": \"view\", \"type\": \"function\"}]" # Simplified ABI; replace with your contract's actual ABI

  Wemix:
    chain_id: 1111 # Example chain ID; replace with actual
    rpc_endpoint: "https://api.wemix.com" # Replace with your RPC endpoint URL
    address: "0x9d7F5C16326dfFcd8CD4C06f0c4DA81fba1B6268" # Your contract's address
    abi: "[{\"constant\": true, \"inputs\": [], \"name\": \"name\", \"outputs\": [{\"name\": \"\", \"type\": \"string\"}], \"payable\": false, \"stateMutability\": \"view\", \"type\": \"function\"}]" # Simplified ABI; replace with your contract's actual ABI

PRIVATE_KEY: ''


